name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.0.16-alpine
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli -h localhost ping" --health-interval 10s --health-timeout 5s --health-retries 15
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true
    - name: yarn install
      run: bin/rails yarn:install
    - name: create database
      run: bin/rails db:create
    - name: create tables
      run: bin/rails db:migrate
    - name: Run tests
      run: bundle exec rake
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        REDIS_DB: 0
